### ISSUE TITLE
Unhandled exception due to service temporarily unavailable

### ISSUE THREAD

**Issue by mrand** [briis/weatherbit#32]
Was a bit surprised to see a stack trace in my logs for something like the service being temporarily unavailable...

2021-04-08 11:03:22 ERROR (MainThread) [custom_components.weatherbit] Unexpected error fetching weatherbit data: Error requesting data from https://api.weatherbit.io/v2.0: 503, message='Service Temporarily Unavailable', url=URL('https://api.weatherbit.io/v2.0/current?lat=32&lon=-97&lang=en&units=M&key=redacted_key')

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/weatherbitpypi/client.py", line 263, in async_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 503, message='Service Temporarily Unavailable', url=URL('https://api.weatherbit.io/v2.0/current?lat=32&lon=-97&lang=en&units=M&key=redacted_key')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 139, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.8/site-packages/weatherbitpypi/client.py", line 48, in async_get_current_data
    return await self._get_current_data()
  File "/usr/local/lib/python3.8/site-packages/weatherbitpypi/client.py", line 74, in _get_current_data
    json_data = await self.async_request("get", endpoint)
  File "/usr/local/lib/python3.8/site-packages/weatherbitpypi/client.py", line 272, in async_request
    raise RequestError(f"Error requesting data from {BASE_URL}: {str(err)}")
weatherbitpypi.errors.RequestError: Error requesting data from https://api.weatherbit.io/v2.0: 503, message='Service Temporarily Unavailable', url=URL('https://api.weatherbit.io/v2.0/current?lat=32&lon=-97&lang=en&units=M&key=redacted_key')

**Comment by briis** [comment]
I will add something to handle this more gracefully. Agree there is no need to do a stack-trace, a warning in the Log would be enough.

**Comment by briis** [comment]
Closing this, as it has been open for a long time, and with the new 1.0.0 release coming out soon, these kind of errors should no longer occur.
