### ISSUE TITLE
Some errors at restarting HA

### ISSUE THREAD

**Issue by gieljnssns** [briis/weatherbit#38]
## System Health

version | core-2021.10.0b6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.70
arch | x86_64
timezone | Europe/Brussels

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4585
Installed Version | 1.15.2
Stage | running
Available Repositories | 958
Installed Repositories | 33

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.5
-- | --
update_channel | beta
supervisor_version | supervisor-2021.09.6
docker_version | 20.10.7
disk_total | 457.7 GB
disk_used | 160.2 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), AdGuard Home (4.1.9), AppDaemon 4 (0.7.0), Caddy (1.6), Check Home Assistant configuration (3.9.0), Duck DNS (1.14.0), ESPHome (2021.9.2), Mosquitto broker (6.0.1), Visual Studio Code (3.6.2), WireGuard (0.5.1), MariaDB (2.4.0), Samba Backup (5.0.0), InfluxDB (4.2.1), Grafana (7.2.0), Frigate NVR (1.14), SSH & Web Terminal (9.0.1), Metabase (0.3.0), Portainer (2.0.0), OwnTone (dev), Simple Scheduler (0.31), Spotify Connect (0.9.1), Glances (0.13.0), phpMyAdmin (0.5.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 17
views | 17
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

```
Logger: homeassistant.components.weather
Source: custom_components/weatherbit/weather.py:140
Integration: Weather (documentation, issues)
First occurred: 18:35:30 (2 occurrences)
Last logged: 18:35:30

Error adding entities for domain weather with platform weatherbit
Error while setting up weatherbit platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 682, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 456, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 496, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/weatherbit/weather.py", line 266, in device_state_attributes
    ATTR_WEATHERBIT_PRECIPITATION: self.precipitation,
  File "/config/custom_components/weatherbit/weather.py", line 140, in precipitation
    return round(float(self._current.precip), 1)
TypeError: float() argument must be a string or a number, not 'NoneType'
```

```
Logger: homeassistant.components.sensor
Source: custom_components/weatherbit/sensor.py:257
Integration: Sensor (documentation, issues)
First occurred: 18:36:18 (2 occurrences)
Last logged: 18:36:18

Error adding entities for domain sensor with platform weatherbit
Error while setting up weatherbit platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 682, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 456, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 489, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 462, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/weatherbit/sensor.py", line 257, in state
    return round(float(value), 1)
TypeError: float() argument must be a string or a number, not 'NoneType'
```

<img width="277" alt="Schermafbeelding 2021-10-05 om 18 43 24" src="https://user-images.githubusercontent.com/17234951/136066390-151bd235-27cc-43b9-be5a-e7a348fb310c.png">

Only `weather`, `snow` and `rain` are unavailable

**Comment by yan14** [comment]
same issue here since updating to 2020.10

**Comment by briis** [comment]
I will look in to this ASAP.

**Comment by yan14** [comment]
It seems that it was solved over night. Strange…

**Comment by briis** [comment]
This normally happens if we are not getting any data or incomplete data from WeatherBit, so unless they close the shop, it should normally resolve itself. But I will put in some error handling to try and prevent crashes and give a better Warning message.

**Comment by briis** [comment]
Closing this. I will still work on the error handling.
