### ISSUE TITLE
 float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Mariusthvdb** [briis/weatherbit#39]
littering the log in 2021.11 dev:
```
2021-10-20 18:54:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 719, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/weatherbit/weather.py", line 266, in device_state_attributes
    ATTR_WEATHERBIT_PRECIPITATION: self.precipitation,
  File "/config/custom_components/weatherbit/weather.py", line 140, in precipitation
    return round(float(self._current.precip), 1)
TypeError: float() argument must be a string or a number, not 'NoneType'
```
and/or
```
2021-10-20 18:54:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 719, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 493, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/weatherbit/sensor.py", line 257, in state
    return round(float(value), 1)
TypeError: float() argument must be a string or a number, not 'NoneType'
```

could this have to do with the new default s for int and float?

__edit__

wait, now see https://github.com/briis/weatherbit/issues/38 which has identical errors logged, but under a non succinct title :-). my pardon.

**Comment by briis** [comment]
No this is not related to the Template change in HA, as this is happening in the IO module that loads data from WeatherBit. It happens when the data you receive is empty, most likely due to a temporary outage at WeatherBit. Normally this resolves itself on the next load of data.
But I will implement some checks for NoneType , so that the system does not throw an error.

**Comment by briis** [comment]
Release 1.0.0, which is due in a few days, is handling these kind of errors much more graceful. So I will close this now.
